services:
  - type: web
    name: legalightstudybot-web
    env: python
    repo: https://github.com/vie2206/legalightstudybot-v2
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: PORT
        value: 10000
